### PR TITLE
Updated Discourse version to the last release

### PR DESCRIPTION
**Pull request by HLFH**
See FYI: https://github.com/discourse/discourse/releases

### CODE REVIEW

**Comment by HLFH** [comment]
@rumpelsepp In fact, the package seems to build, but I don't see any install at allL The files are staying in /tmp/pacaurtmp-hlfh/discourse/...

**Comment by rumpelsepp** [comment]
I prefer keeping stable releases in AUR; the latest stable is 1.4.3. For beta releases one could easily create a discourse-beta package. Have you built a package using `makepkg -si`; I just updated today and it worked.

> Are you still a maintainer of the package?
Yeah, just a bit busy these days...

**Comment by rumpelsepp** [comment]
Should be fixed now.

**Comment by HLFH** [comment]
@rumpelsepp Thanks!!! it works. You're a magician.

**Pull request closed without merging**
